version: '3.4'

services:
  tentime.administrationservice.httpapi.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44313
      - ASPNETCORE_Kestrel__Certificates__Default__Password=TenTime123#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/mifteam.pfx
    ports:
      - "44313:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
